Add IaC scripts
wso2/iac-gcp-wso2-products pull request #2
Opened 2023-11-21 05:36 UTC by PasanT9

## Purpose
> Deploy a Google Kubernetes Engine (GKE) cluster with an integrated bastion server.
> Additionally, there's an option to enable supplementary elements like MySQL, filestore, and secrets based on your requirements.

2024-01-04 06:25 UTC, ThilinaManamgoda requested changes

2024-01-04 06:25 UTC, ThilinaManamgoda commented on alerts.tf
> +  source              = "git::https://github.com/wso2/gcp-terraform-modules.git//modules/gcp/Notification-Channel"
Shall we create a tag from this repo and refer to a particular tag. This is applicable for all the source references.

2024-01-04 06:25 UTC, ThilinaManamgoda commented on filestore.tf
> +# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
Let's change the license header year to 2024 on all occurrences

2024-11-07 06:24 UTC, RakhithaRR approved these changes

2024-11-11 03:51 UTC, merged